[package]
name = "protonvpn"
version = "0.1.0"
authors = ["hybras <24651269+hybras@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
lazy_static = "1.4"
dirs = "3.0.1"
literally = "0.1.3"
url = {version = "2.1.1", features = ["serde"]}
serde = "1.0"
